### ISSUE TITLE
Won't Update BepInEx

### ISSUE THREAD

**Issue by cbass888** [WFIOST/H3VRModInstaller#37]
Mod loader refuses to download the newer edition of BepInEx, only downloads 5.4.8 and not 5.4.9 which causes issues with newer mods (PMC Pete mainly). Loader NOT installed in same folder as H3VR base game

**Comment by Frityet** [comment]
uh there is no reason why bepinex 5.4.9 should have trouble with TNHTweaker

**Comment by cbass888** [comment]
I'm aware, the mod loader refuses to load the new one and the old one that
it would load (even after clicking the update button)would not work with
the tnhtweaker 3.0 as it would only update to the older bepinex 5.8
