### ISSUE TITLE
Installer puts mods in old game location, not the new location

### ISSUE THREAD

**Issue by Johnnyjr100** [WFIOST/H3VRModInstaller#42]
**Describe the bug**
After moving H3VR to a different steam library, modinstaller installs mod to the old library, not the actual game.

**To Reproduce**
Move H3VR from one library to another.
Attempt to install mods

**Expected behavior**
I expected it to install to the correct folder

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 V20H2

**Comment by Frityet** [comment]
Hey sorry for late reply, this is an error with how modinstaller detects h3vr install location, and is fixed in te next update with the inclusion of an options panel which lets you pick path
